### ISSUE TITLE
Inconvenient return type of `sscan`

### ISSUE THREAD

**Issue by ylxdzsw** [JuliaDatabases/Redis.jl#28]
`sscan` returns a Set, containing only two elements: an Integer cursor and an Array of values.

```
julia> for i in 1:100 sadd(conn, "test", "test$i") end

julia> sscan(conn, "test", 0)
Set(Any["56",Any["test20","test3","test65","test90","test30","test2","test97","test28","test61","test83"]])

julia> sscan(conn, "test", 0) |> typeof
Set{Any}
```

It's not easy to get the cursor and values from `Set`, and I think it's a bug. For me, a better return type can be `Tuple{Int, Set}`, or just `Array` contains both the cursor and values as what `scan` does.

**Comment by ylxdzsw** [comment]
After I read the source, I believe it is a bug in `*scan` methods, which return not only the values but a cursor. I am trying to fix them by making them returns a Tuple{Int, T} instead.

**Comment by jkaye2012** [comment]
Thanks for the contribution. The basics of your PR look good - just need to add a few tests in there then this can be merged and resolved.
