### ISSUE TITLE
Julia 1.0 support and possible moving repo to JuliaDatabases

### ISSUE THREAD

**Issue by GearsAD** [JuliaDatabases/Redis.jl#51]
Great library - thank you for writing! It's not Julia 1.0 compliant, so I've created a fork with updates - it is WIP right now but most of the functionality works - [Redis.jl fork](https://github.com/GearsAD/Redis.jl). If it looks good I can make a PR to update your repo.

For continued maintenance, what are your thoughts on moving this to JuliaDatabases organization? You put a lot of work into it and wouldn't want it to go to waste.

**Comment by jkaye2012** [comment]
I'm for it. I actually think I might've even created an issue about that
some time ago. I haven't had much time to work with Julia lately, so I'd be
happy to move this over so that others can continue to improve upon it!

**Comment by GearsAD** [comment]
Great! If you like I'll find out about moving it while finishing up the 1.0 upgrade. Should take me a few days to get the tests running cleanly.

**Comment by GearsAD** [comment]
Upgraded and everything seems to be working - this is in PR #52.

**Comment by dehann** [comment]
+1

**Comment by jkaye2012** [comment]
Sorry for the delay, I've been busy. Hoping to get to this tomorrow.

**Comment by GearsAD** [comment]
Great, thank you for merging! 

I have access to JuliaDatabases, still good to transfer ownership to that organization?

**Comment by Affie** [comment]
+1 It would be great to have all the database stuff in one place and increase the amount of people that can maintain it.

**Comment by jkaye2012** [comment]
I will be doing this! I'm on my honeymoon currently, so it'll have to wait
until I'm back, but I agree that a central repo makes more sense for the
library at this point.

**Comment by GearsAD** [comment]
Congratulations on wedding! Sure, no rush, in the interim i've created a tag on the fork that I'm using.

**Comment by dehann** [comment]
Hi, congrats as well!

Could I ask to move this repo to JuliaDatabases perhaps please?

**Comment by staples6** [comment]
Hi, is there going to be continued support for this package for Julia 1.0 and beyond? Is this still planned to move to JuliaDatabases?

**Comment by jkaye2012** [comment]
I would like to, but never received a response to the above. I suppose I could reach out directly to them, time has just been limited lately for me. I am happy to move the repo.

**Comment by staples6** [comment]
@GearsAD is this something you can still support?

**Comment by jpsamaroo** [comment]
@GearsAD I believe you'll need to add the package author as a member of the org first, and then they can transfer it themselves. I may also be wrong; I'm just speaking from experience from when I moved some personal repos to JuliaIO.

**Comment by staples6** [comment]
@jkaye2012 I got a response from @quinnj and he is willing to help with transferring the repo to the JuliaDatabases org

**Comment by quinnj** [comment]
I went ahead and added @jkaye2012 as a member of JuliaDatabases, so that should be sufficient to transfer the repo over. Let me know if you run into any snags along the way and I can help out.

**Comment by GearsAD** [comment]
Great - thanks @quinnj 

Sorry been on another project, but if this needs updating to get it compatible for 1.1/1.2 I can support.

**Comment by jkaye2012** [comment]
I plan on taking care of this sometime this weekend. Thanks.

**Comment by jkaye2012** [comment]
Apologies for the delay, but this is now complete 👍

**Comment by woshidama323** [comment]
Great project . @jkaye2012 
When I install this by using Pkg Add. I got some errors 
```
(v1.1) pkg> add Redis
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Redis [0cf705f9]:
 Redis [0cf705f9] log:
 ├─possible versions are: [0.0.1-0.0.2, 0.1.0-0.1.1] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.0.1-0.0.2, 0.1.0-0.1.1]
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
```

Could you help to check this , the New version hasn't been released ?

**Comment by staples6** [comment]
a new version will need to be tagged. try
```julia
]add Redis#master
```

**Comment by jkaye2012** [comment]
@GearsAD now that the project is part of JuliaDatabases, is there anything different that should be done for tagging new releases? I think there is also an open bug in unsubscribe that needs to be fixed before we tag the new version.
