### ISSUE TITLE
Is RedisConnection with multiple threads (for reading) safe?

### ISSUE THREAD

**Issue by shivchawla** [JuliaDatabases/Redis.jl#54]
Is RedisConnection with multiple threads (for reading) safe? 

I am trying to expedite reading different keys in a 8 core machine but it's crashing in a threaded environment.

**Case 1: Using same connection** (crashes)
```
connection  = RedisConnection(host="127.0.0.1", port=6379, db=0, password="")

Threads.@threads for i in 1:10
     members = smembers(connection, some_key)
end

```

**Case 2: Using separate connection** (crashes)
```
connections = Vector{RedisConnection}(undef, 10)

for i in 1:10
     connections[i]  = RedisConnection(host="127.0.0.1", port=6379, db=0, password="")
end

Threads.@threads for i in 1:10
     members = smembers(connection[i], some_key)
end

```
I am not sure if it's package specific issue so apologize if it doesn't belong here.

Thanks!

**Comment by jpsamaroo** [comment]
This isn't package specific, Julia's fork of libuv is not yet thread-safe (so any TCPSocket operations aren't thread-safe either).

**Comment by shivchawla** [comment]
Thanks for the clarification. Do you know if the Julia Team has plans to make it thread safe (in case you are aware of such communication)?

**Comment by jpsamaroo** [comment]
Sorry, this seemed to slip past my notice until I went through my email today. Yes, making Julia thread-safe is definitely the goal. Currently, master has seen a lot of work to support this goal, and so if your MWEs above don't work on today's master, it may not be much more to get them there.

If you're still interested in this, maybe you can try running your MWE again on Julia master and report back on whether it crashes?

**Comment by jkaye2012** [comment]
I am going to close this out as it does not seem to be directly related to the package - please let me know if I should reopen.
