### ISSUE TITLE
Use with RedisGraph ?

### ISSUE THREAD

**Issue by MorganeAlinai** [JuliaDatabases/Redis.jl#60]
Hi, 

I was wondering if this could be usable with RedisGraph ?

In the most basic way, RedisGraph will only need the ability to pass raw Redis commands.

Otherwise, a serie of Keywords may be added.

https://oss.redislabs.com/redisgraph/#using-redisgraph

Regards

**Comment by jkaye2012** [comment]
Adding support for something like this should not be very difficult. If you take a peek at the code, most of the actual commands are implemented using macros. I am not very familiar with RedisGraph, but unless their commands are very complex, the existing macros should be able to model them.

**Comment by jkaye2012** [comment]
Great! I'm going to close this issue, but if you'd like to submit a pull request to make mention of the integration in the readme, I would be happy to merge it.
