### ISSUE TITLE
Re-register package

### ISSUE THREAD

**Issue by staples6** [JuliaDatabases/Redis.jl#69]
This package was removed from the General registry. Is it possible to re-register it now that it's compatible with julia 1.0?

**Comment by jkaye2012** [comment]
I would gladly accept a pr for that. I haven't kept up with the Julia
ecosystem for a while and my last attempt failed for some reason that I
didn't have time to look into.

**Comment by staples6** [comment]
My understanding is that one of the owners of the repo will need to install the Registrator GitHub app and then can register through an issue or commit comment: https://github.com/JuliaRegistries/Registrator.jl

**Comment by jkaye2012** [comment]
This is being resolved here: tagging-compat
