### ISSUE TITLE
key expiration callback

### ISSUE THREAD

**Issue by weera-tech** [JuliaDatabases/Redis.jl#70]
I need to define some callback functions on key expiration events. Is it possible using this package?

**Comment by jkaye2012** [comment]
Key expirations are broadcast through the pub/sub system (or at least they
were when I was using redis actively a few years ago). So you should be
able to subscribe to those events to fire your callbacks.

**Comment by weera-tech** [comment]
Thank you for reply, could you please show it in a code block here? I am new to julia and I really need this

**Comment by weera-tech** [comment]
After some effort, I know that I have two issues:
1. I need to define publish on expiration time of keys. publish should call immediately after expiration and I don't know how.
2. I should get key name in publish third argument "foobar". and I don't know how too!

**Comment by weera-tech** [comment]
Update:
for channel **__keyevent@15__:expired** and callback function **f(chan, key)** I got this Error:
MethodError(Redis.SubscriptionMessage, ("OK",), 0x0000000000006a57)

**Comment by jkaye2012** [comment]
If this is still a problem, could you please show a small example of the code that you're trying to write to do this?

**Comment by jkaye2012** [comment]
Inactive
