### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by david-macmahon** [JuliaDatabases/Redis.jl#82]
Since PR #81 has been merged into master, it would be nice to have that fix/functionality available as a tagged release rather than having to use `Redis.jl#master` to get it.  I think it is technically breaking since it changes the value passed to subscription handler functions, so maybe v1.1.0?

**Comment by david-macmahon** [comment]
I just noticed that `Project.toml` on master already specifies the version as v1.1.0 so I guess it just needs to be tagged as such.

**Comment by jkaye2012** [comment]
Hi David,

I'm happy to tag a new release. I think the process for this changed within the past year or so (maybe earlier) and I have not been actively keeping up with the Julia ecosystem since then. Is this something that can be resolved with a PR or should I be looking into setting up some new CD for the repo?

**Comment by mmiller-max** [comment]
I think the breaking change means that it should be v2.0.0 - any package with a compat field set to 1 or 1.1 could break if the version only goes up to 1.1.0.

The easiest way to register now is to use @JuliaRegistrator and @JuliaTagBot.

It may be worth thinking if there are any other breaking changes that may want to be done, and lumping them in together?

**Comment by jkaye2012** [comment]
I'm unaware of any pending changes that would necessitate a major version bump. #76 is the only open feature request right now, which would be additive and only a minor bump.

**Comment by mmiller-max** [comment]
I was thinking that #81 technically changes the public API (subscription callback function now receives different inputs to before), and therefore needs a major version bump as it's a breaking change.

**Comment by jkaye2012** [comment]
Sorry, yes I agree with that. I meant there aren't any others pending.

**Comment by mmiller-max** [comment]
Ah of course, sorry for misunderstanding

**Comment by pankgeorg** [comment]
Bump on this; is there something we can help with?

Thanks!

**Comment by jkaye2012** [comment]
If you'd like to tag/upload the release, I would be happy to accept a PR for this
