### ISSUE TITLE
Github Release 2.0

### ISSUE THREAD

**Issue by ShalokShalom** [JuliaDatabases/Redis.jl#93]
Hi there :)

A merge for 2.0 has been not followed yet with a public release on Github. 

https://github.com/JuliaDatabases/Redis.jl/commit/1f54a3cf55427ee6d77d27ac38cb3d06b88993b3

Linux Distributions, and many other (CI) services depend on those, so please release 2.0 on Github as well.

**Comment by jkaye2012** [comment]
Sure, done.
